### PR TITLE
Fix: Move AccordionList to a directory/Change to Arrow Function

### LINKED ISSUE #25: convert AccordionList to arrow function
https://github.com/aaron-org/snapit-hacktoberfest/blob/d13b3b6ac5ee5b963956eaf8b0e204f13ac6aa9b/src/components/AccordionList.jsx#L22

Convert this component to an arrow function, and move the export to the bottom like in other components.

### LINKED ISSUE #49: Move AccordionList to a directory
Currently AccordionList is inside the components directory, but it should have its own directory within the components directory.

### PR DESCRIPTION
**Pull request by camitaylor**
# [Fix Move AccordionList/Change to Arrow Function](https://trello.com/c/AqccUMDe/8-create-faq-page)

## A short description of what this PR does.
As a Developer, I want the AccordionList files to be in their own directory. 
Fixes #49  
Fixes #25 

## How was it tested?
This was linted with Yarn and tested with Jest.

Screen Shot 2021-09-23 at 12 49 36 PM

### Yarn Lint

Screen Shot 2021-09-23 at 12 50 06 PM

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/aaronshivers/snapit-hacktoberfest/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

### CODE REVIEW

File: src/pages/FAQ/FAQ.jsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import React from "react";
 import Box from "@mui/material/Box";
-import AccordionList from "../../components/AccordionList";
+import AccordionList from "../../components/AccordionList/AccordionList";
```
Comment (aaronshivers) [inline src/pages/FAQ/FAQ.jsx:3]: 🔧 Add an `index.jsx` file, and import like this: `import AccordionList from "../../components/AccordionList";`

**Review by aaronshivers — CHANGES_REQUESTED** [review]

File: src/pages/FAQ/FAQ.jsx (hunk 1 above)
Comment (camitaylor) [reply src/pages/FAQ/FAQ.jsx]: Addressed: commit ba67774be0fa48ace3814e246d359199099aef84

**Review by aaronshivers — APPROVED** [review]

**Comment by aaronshivers** [comment]
🔧 rebase
